import Head from 'next/head'

import { UserButton } from '@clerk/nextjs'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            go to sign-in <a href='https://accounts.shehzadakbar.com/sign-in'>here</a>
          </p>
          <div>
          <UserButton afterSignOutUrl='/' />
          </div>
        </div>
      </main>
    </>
  )
}
